#!/bin/sh -e

docker_username="${DOCKER_USERNAME:-vallyian}"
docker_repo="${DOCKER_REPO:-media-share}"
github_main="${GITHUB_MAIN:-false}"
new_version="${NEW_VERSION}"
github_sha="${GITHUB_SHA}"
semver="${SEMVER:-0.0.0}"
npm_audit_level="${NPM_AUDIT_LEVEL:-low}"
trivy_severity="${TRIVY_SEVERITY:-UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL}"
ignore_smoke_test_result=true
artifacts_dir="${PWD}/artifacts"

main() { case "${1}" in
    "semver"  ) semver  ;;
    "build"   ) build   ;;
    "test"    ) test    ;;
    "scan"    ) scan    ;;
    "results" ) results ;;
    "push"    ) push    ;;

    *) term "USAGE:   ./run   semver | build | test | results | scan | push"
esac }
term() { echo "\033[0;31m${1}\033[0m"; exit 1; }

####################################################################################################

semver() {
    [ "${new_version}" != "" ] || term "semver can only run in CI"

    if [ "${github_main}" = "true" ]; then
        echo "::set-output name=SEMVER::${new_version}"
        echo "SEMVER: ${new_version}"
    else
        echo "::set-output name=SEMVER::${new_version}-${github_sha}"
        echo "SEMVER: ${new_version}-${github_sha}"
    fi
}

build() {
    rm -rf artifacts

    docker buildx build \
        `[ ${github_sha} = "" ] || echo --pull` \
        --target export \
        --output=type=local,dest=artifacts \
        .

    docker buildx build \
        -t ${docker_username}/${docker_repo}:${semver} \
        --build-arg "NPM_AUDIT_LEVEL=${npm_audit_level}" \
        --build-arg "SEMVER=${semver}" \
        `[ ${github_sha} = "" ] || echo --pull` \
        --output=type=docker \
        .

    docker image inspect ${docker_username}/${docker_repo}:${semver} > /dev/null
}

test() {
    local container=${docker_username}-${docker_repo}-${semver}
    local cert_crt="${PWD}/server/certs/cert.crt"
    local cert_key="${PWD}/server/certs/cert.key"
    local test_failed=true
    local smoke_test_dir="${artifacts_dir}/smoke-test"
    local media_dir="${smoke_test_dir}/test-dir"
    local test_result="${smoke_test_dir}/smoke-test.txt"

    rm -rf "${smoke_test_dir}"
    mkdir -p "${media_dir}"
    echo "test file" > "${media_dir}/test-file"

    if [ ! -f "${cert_crt}" ] || [ ! -f "${cert_key}" ]; then
        echo "creating test self-signed certs..."
        mkdir -p server/certs
        openssl req -new -newkey rsa:4096 -days 1 -nodes -x509 \
            -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" \
            -out "${cert_crt}" -keyout "${cert_key}"
    fi

    echo "starting service..."
    (docker stop ${container} && docker rm ${container} || echo "container ${container} not running") && \
    docker run --name ${container} --rm --detach \
        -v "${smoke_test_dir}:/home/node/app/media" \
        -v "${cert_crt}:/run/secrets/cert.crt:ro" \
        -v "${cert_key}:/run/secrets/cert.key:ro" \
        -e "G_CLIENT_ID=test.apps.googleusercontent.com" \
        -e "G_EMAILS=test@gmail.com" \
        -p "127.0.0.1:58081:58082" \
        ${docker_username}/${docker_repo}:${semver}

    echo "waiting for service to become available..."
    timeout 30s bash -c 'while [[ "$(curl --insecure https://localhost:58081/health)" != "healthy" ]]; do sleep 5; done'

    curl --insecure --verbose https://localhost:58081/test-dir/test-file > "${test_result}" 2>&1

    if grep -Fq "GET /test-dir/test-file HTTP/1.1"   "${test_result}" \
    && grep -Fq "HTTP/1.1 401 Unauthorized"          "${test_result}"; \
    then test_failed=false; fi

    docker stop ${container}
    rm -rf "${media_dir}"

    if [ "${test_failed}" = "true" ]; then
        echo "smoke test failed"
        [ "ignore_smoke_test_result" = "false" ] || term
    fi
}

scan() {
    docker run \
        --rm \
        --pull always \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v ${HOME}/.trivy/cache:/root/.cache \
        -v ${PWD}:/config \
        aquasec/trivy \
            image \
                --exit-code=1 \
                --severity "${trivy_severity}" \
                ${docker_username}/${docker_repo}:${semver}
}

results() {
    local errors=""

    [ ! -f ${artifacts_dir}/npm-test.fail    ] || errors="npm test failed\n${errors}"
    # [ ! -f ${artifacts_dir}/npm-lint.fail    ] || errors="npm lint failed\n${errors}"
    [   -f ${artifacts_dir}/unit-tests/*.xml ] || errors="npm test results not found\n${errors}"

    if [ "${errors}" != "" ]; then
        term "${errors}"
    fi
}

push() {
    [ "${semver}" != "0.0.0" ] || term "push can only run in CI"

    docker buildx build \
        -t ${docker_username}/${docker_repo}:${semver} \
        -t ${docker_username}/${docker_repo}:latest \
        --build-arg "SEMVER=${semver}" \
        --platform "linux/amd64,linux/arm64/v8" \
        --pull \
        --output=type=registry \
        .
}

main "$@"
