#!/bin/sh -e

docker_username="${DOCKER_USERNAME:-vallyian}"
docker_repo="${DOCKER_REPO:-media-share}"
github_main="${GITHUB_MAIN:-false}"
new_version="${NEW_VERSION}"
github_sha="${GITHUB_SHA}"
semver="${SEMVER:-0.0.0}"
npm_audit_level="${NPM_AUDIT_LEVEL:-low}"
trivy_severity="${TRIVY_SEVERITY:-UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL}"
artifacts_dir="${PWD}/artifacts"

term() { echo "\033[0;31m${1}\033[0m"; exit 1; }

semver() {
    [ "${new_version}" != "" ] || term "semver can only run in CI"

    if [ "${github_main}" = "true" ]; then
        echo "::set-output name=SEMVER::${new_version}"
        echo "SEMVER: ${new_version}"
    else
        echo "::set-output name=SEMVER::${new_version}-${github_sha}"
        echo "SEMVER: ${new_version}-${github_sha}"
    fi
}

build() {
    rm -rf artifacts

    docker buildx build \
        $([ "${github_sha}" = "" ] || echo --pull) \
        --target export \
        --output=type=local,dest=artifacts \
        .

    docker buildx build \
        $([ "${github_sha}" = "" ] || echo --pull) \
        -t ${docker_username}/${docker_repo}:${semver} \
        --build-arg "NPM_AUDIT_LEVEL=${npm_audit_level}" \
        --build-arg "SEMVER=${semver}" \
        --output=type=docker \
        .

    docker image inspect ${docker_username}/${docker_repo}:${semver} > /dev/null
}

test_result() {
    curl --insecure --verbose https://localhost:58081${1} > "${2}" 2>&1 || return 1
    grep -Fq "GET ${1} HTTP/1.1"         "${2}" || return 2
    grep -Fq "HTTP/1.1 401 Unauthorized" "${2}" || return 3
    return 0
}
test() {
    local container=${docker_username}-${docker_repo}-${semver}-smoke-test
    local smoke_test_dir="${artifacts_dir}/smoke-test"
    local media_share_dir="${smoke_test_dir}/media"
    local media_certs_dir="${smoke_test_dir}/certs"
    local cert_crt="${media_certs_dir}/cert.crt"
    local cert_key="${media_certs_dir}/cert.key"
    local media_test_dir="${media_share_dir}/test-dir"
    local container_logs="${smoke_test_dir}/container-logs.txt"
    local test_failed=""

    echo "removing smoke test data..."
    rm -rf "${smoke_test_dir}"

    echo "creating media test data..."
    mkdir -p "${media_test_dir}"
    echo "test file" > "${media_test_dir}/test-file"

    echo "creating test self-signed certs..."
    mkdir -p "${media_certs_dir}"
    openssl req -new -newkey rsa:4096 -days 1 -nodes -x509 \
        -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=127.0.0.1" \
        -out "${cert_crt}" -keyout "${cert_key}"

    chmod -R 777 "${smoke_test_dir}"

    echo "starting service..."
    (docker stop ${container} > /dev/null 2>&1 && docker rm ${container} > /dev/null 2>&1) || echo "container ${container} not running"
    docker run --name ${container} --rm \
        -p "58081:58082" \
        -v "${media_share_dir}:/home/node/app/media" \
        -v "${media_certs_dir}/cert.crt:/run/secrets/cert.crt:ro" \
        -v "${media_certs_dir}/cert.key:/run/secrets/cert.key:ro" \
        -e "AUTH_CLIENT=test.apps.googleusercontent.com" \
        -e "AUTH_EMAILS=test@gmail.com" \
        -e "DEBUG=*" \
        ${docker_username}/${docker_repo}:${semver} &

    if timeout 30s sh -c 'while [ "$(curl --insecure https://localhost:58081/health)" != "healthy" ]; do sleep 5; done'; then
        local requestId=1
        test_result "/test-dir" "${smoke_test_dir}/curl-${requestId}.txt" || test_failed="${test_failed}${requestId},"
        local test_result_code=$?
        [ "${test_result_code}" = "0" ] || test_failed="${test_failed}${requestId},"

        local requestId=2
        test_result "/test-dir/test-file" "${smoke_test_dir}/curl-${requestId}.txt" || test_failed="${test_failed}${requestId},"
        local test_result_code=$?
        [ "${test_result_code}" = "0" ] || test_failed="${test_failed}${requestId},"
    else
        echo "FAIL: GET /health - does not contain 'healthy'"
    fi

    docker logs ${container} > "${container_logs}" 2>&1 || echo "docker logs cmd failed"
    docker stop ${container} || echo "docker stop cmd failed"

    [ "${test_failed}" = "" ] || term "smoke test (${test_failed}) failed"
}

scan() {
    docker run \
        --rm \
        --pull always \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v ${HOME}/.trivy/cache:/root/.cache \
        aquasec/trivy \
            image \
                --exit-code=1 \
                --severity "${trivy_severity}" \
                ${docker_username}/${docker_repo}:${semver}
}

results() {
    local errors=""

    [ ! -f ${artifacts_dir}/npm-test.fail    ] || errors="npm test failed\n${errors}"
    # [ ! -f ${artifacts_dir}/npm-lint.fail    ] || errors="npm lint failed\n${errors}"
    [   -f ${artifacts_dir}/unit-tests/*.xml ] || errors="npm test results not found\n${errors}"

    [ "${errors}" = "" ] || term "${errors}"
}

push() {
    [ "${semver}" != "0.0.0" ] || term "push can only run in CI"

    local latest_tag
    [ "${github_main}" = "true" ] && \
    latest_tag="-t ${docker_username}/${docker_repo}:latest" || \
    latest_tag=""

    docker buildx build \
        ${latest_tag} \
        -t ${docker_username}/${docker_repo}:${semver} \
        --build-arg "SEMVER=${semver}" \
        --platform "linux/amd64,linux/arm64/v8" \
        --pull \
        --output=type=registry \
        .
}

dev() {
    [ -f "./server/.env" ] && export $(echo $(cat "./server/.env" | sed 's/#.*//g'| xargs) | envsubst)
    [ "${MEDIA_SHARE_DIR}" = "" ] && term "missing env var MEDIA_SHARE_DIR"
    [ -d "${MEDIA_SHARE_DIR}" ] || term "dir \"${MEDIA_SHARE_DIR}\" not found"
    [ "${AUTH_CLIENT}" = "" ] && term "missing env var AUTH_CLIENT"
    [ "${AUTH_EMAILS}" = "" ] && term "missing env var AUTH_EMAILS"

    build

    local container=${docker_repo}-${semver}

    docker stop ${container} > /dev/null && docker rm ${container} > /dev/null || echo "container ${container} not running"
    docker run --name ${container} --rm \
        -p "127.0.0.1:58081:58082" \
        -v "${MEDIA_SHARE_DIR}:/home/node/app/media" \
        $([ "${MEDIA_CERTS_DIR}" != "" ] && [ -d "${MEDIA_CERTS_DIR}" ] && echo -v "${MEDIA_CERTS_DIR}/cert.crt:/run/secrets/cert.crt:ro") \
        $([ "${MEDIA_CERTS_DIR}" != "" ] && [ -d "${MEDIA_CERTS_DIR}" ] && echo -v "${MEDIA_CERTS_DIR}/cert.key:/run/secrets/cert.key:ro") \
        -e "NODE_ENV=development" \
        -e "AUTH_CLIENT" \
        -e "AUTH_EMAILS" \
        -e "COOKIE_PASS" \
        -e "TOKEN_KEY" \
        ${docker_username}/${docker_repo}:${semver}
}

prod() {
    [ "${MEDIA_SHARE_DIR}" = "" ] && term "missing env var MEDIA_SHARE_DIR"
    [ -d "${MEDIA_SHARE_DIR}" ] || term "dir \"${MEDIA_SHARE_DIR}\" not found"
    [ "${MEDIA_CERTS_DIR}" = "" ] && term "missing env var MEDIA_CERTS_DIR"
    [ -d "${MEDIA_CERTS_DIR}" ] || term "dir \"${MEDIA_CERTS_DIR}\" not found"

    build

    semver=latest
    local container=${docker_repo}-${semver}

    docker stop ${container} > /dev/null && docker rm ${container} > /dev/null || echo "container ${container} not running"
    docker run --name ${docker_repo} --pull always --restart=always -d \
        -p "127.0.0.1:58080:58082" \
        -v "${MEDIA_SHARE_DIR}:/home/node/app/media" \
        -v "${MEDIA_CERTS_DIR}/cert.crt:/run/secrets/cert.crt:ro" \
        -v "${MEDIA_CERTS_DIR}/cert.key:/run/secrets/cert.key:ro" \
        -e "AUTH_CLIENT" \
        -e "AUTH_EMAILS" \
        ${docker_username}/${docker_repo}:${semver}
}

case "${1}" in
    "semver"  ) semver  ;;
    "build"   ) build   ;;
    "test"    ) test    ;;
    "scan"    ) scan    ;;
    "results" ) results ;;
    "push"    ) push    ;;
    "dev"     ) dev     ;;
    "prod"    ) prod    ;;

    *) term "USAGE:   ./run   semver | build | test | results | scan | push | dev | prod"
esac
