name: ci

on:
    push:
        branches: [main]
        paths-ignore: ["**/*.md"]

    pull_request:
        branches: [main]
        paths-ignore: ["**/*.md"]

    workflow_dispatch:
        inputs:
            publish_image:
                description: "Push runtime image to Docker Hub"
                default: "false"
                required: false

jobs:
    semver:
        name: Semantic version
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

            - name: Tag version
              id: tag
              uses: mathieudutour/github-tag-action@d745f2e74aaf1ee82e747b181f7a0967978abee0 # v6.0
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  dry_run: ${{ github.ref != 'refs/heads/main' }}
                  create_annotated_tag: true
                  release_branches: "^main$"

            - name: Calc semver
              env:
                  GITHUB_MAIN: ${{ github.ref == 'refs/heads/main' }}
                  NEW_VERSION: ${{ steps.tag.outputs.new_version }}
                  GITHUB_SHA: ${{ github.sha }}
              run: ./run semver

        outputs:
            SEMVER: ${{ steps.semver.outputs.SEMVER }}

    build-test:
        name: Build and test
        runs-on: ubuntu-latest
        needs: [semver]

        steps:
            - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

            - uses: docker/setup-qemu-action@8b122486cedac8393e77aa9734c3528886e4a1a8 # v2.0.0

            - uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6 # v2.0.0

            - name: Build, test and extract artifacts
              env:
                  SEMVER: ${{needs.semver.outputs.SEMVER}}
              run: ./run build

            - name: Run smoke test
              env:
                  SEMVER: ${{needs.semver.outputs.SEMVER}}
              run: ./run test

            - uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # v3.1.0
              if: always()
              with:
                  name: artifacts
                  path: artifacts

            - uses: EnricoMi/publish-unit-test-result-action@2a60c5d47eb29cd5cc922f51bbea18e148f56203 # v2.0.0
              if: always()
              with:
                  github_token: ${{secrets.GITHUB_TOKEN}}
                  junit_files: artifacts/unit-tests/*.xml
                  fail_on: "test failures"

            - name: Scan runtime image
              env:
                  SEMVER: ${{needs.semver.outputs.SEMVER}}
                  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
              run: ./run scan

            - name: Check results
              run: ./run results

            - uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b # v2.0.0
              if: ${{ github.ref == 'refs/heads/main' || github.event.inputs.publish_image == 'true' }}
              with:
                  username: ${{secrets.DOCKER_USERNAME}}
                  password: ${{secrets.DOCKER_PASSWORD}}

            - name: Build and push multiplatform runtime image to Docker Hub
              if: ${{ github.ref == 'refs/heads/main' || github.event.inputs.publish_image == 'true' }}
              env:
                  SEMVER: ${{needs.semver.outputs.SEMVER}}
                  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
              run: ./run push
