name: ci

on:
    workflow_dispatch:
        inputs:
            my_input:
                description: "..."
                default: "my secret value"
                required: false

jobs:
    test:
        name: test
        runs-on: ubuntu-latest

        steps:
            - name: mask
              if: ${{ github.event.inputs.my_input }}
              env:
                  my_input: ${{ github.event.inputs.my_input }}
              run: |
                  echo "::add-mask::${my_input}"
                  echo "should be masked ${my_input}"

            - name: check 1
              env:
                  my_input: ${{ github.event.inputs.my_input }}
              run: echo "should be masked ${my_input}"
  
            - name: check 2
              run: echo "should be masked ${{ github.event.inputs.my_input }}"
