name: ci

on:
    push:
        branches: [main]
        paths-ignore:
            - ".vscode/**"
            - "**/*.md"
    pull_request:
        branches: [main]
        paths-ignore:
            - ".vscode/**"
            - "**/*.md"

jobs:
    semver:
        name: Semantic version
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

            - name: Github env
              id: github_env
              env:
                GITHUB_MAIN: ${{ github.ref == 'refs/heads/main' }}
              run: echo "::set-output name=GITHUB_MAIN::${GITHUB_MAIN}"

            - name: Tag version
              id: tag_version
              uses: mathieudutour/github-tag-action@d745f2e74aaf1ee82e747b181f7a0967978abee0 # v6.0
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                dry_run: ${{ steps.github_env.outputs.GITHUB_MAIN != 'true' }}
                create_annotated_tag: true
                release_branches: "^main$"

            - name: Calc semver
              id: calc_semver
              env:
                GITHUB_SHA: ${{ github.sha }}
                GITHUB_MAIN: ${{ steps.github_env.outputs.GITHUB_MAIN }}
                SEMVER: ${{ steps.tag_version.outputs.new_version }}
              run: |
                if [ "${GITHUB_MAIN}" = "true" ]; then
                    echo "SEMVER: ${SEMVER}"
                    echo "::set-output name=SEMVER::${SEMVER}"
                else
                    echo "SEMVER: ${SEMVER}-${GITHUB_SHA}"
                    echo "::set-output name=SEMVER::${SEMVER}-${GITHUB_SHA}"
                fi

        outputs:
            GITHUB_MAIN: ${{ steps.github_env.outputs.GITHUB_MAIN }}
            SEMVER: ${{ steps.calc_semver.outputs.SEMVER }}

    build-test:
        name: Build and test
        runs-on: ubuntu-latest
        needs:
            - semver
        env:
            DOCKER_REPO: media-share
            SEMVER: ${{ needs.semver.outputs.SEMVER }}

        steps:
            - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

            - uses: docker/setup-qemu-action@8b122486cedac8393e77aa9734c3528886e4a1a8 # v2.0.0

            - uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6 # v2.0.0

            - name: Log in to Docker Hub
              uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7 # v1.14.1
              if: ${{ needs.semver.outputs.GITHUB_MAIN == 'true' }}
              with:
                username: ${{secrets.DOCKER_USERNAME}}
                password: ${{secrets.DOCKER_PASSWORD}}

            - name: Build, test and extract artifacts
              run: docker buildx build --pull --target export -o artifacts .

            - name: Build multiplatform runtime and push
              if: ${{ needs.semver.outputs.GITHUB_MAIN == 'true' }}
              run: |
                docker buildx build \
                  -t ${{secrets.DOCKER_USERNAME}}/${DOCKER_REPO}:${SEMVER} \
                  -t ${{secrets.DOCKER_USERNAME}}/${DOCKER_REPO}:latest \
                  --pull \
                  --build-arg SEMVER \
                  --platform linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x \
                  --push \
                  .
