name: ci

on:
    workflow_dispatch:
        inputs:
            my_input:
                description: "..."
                default: "my secret value"
                required: true

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: mask
              run: echo "::add-mask::$(jq -r '.inputs.my_input' $GITHUB_EVENT_PATH)"

            - name: test - direct input usage
              run: echo "should be masked ${INPUT_MY_INPUT}"

            - name: test - indirect input usage with env var
              env:
                  my_input: ${{ github.event.inputs.my_input }}
              run: echo "should be masked ${my_input}"
